[package]
name = "mftree"
version = "0.1.0"
edition = "2021"
description = "家系図自動生成"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
rand_pcg = "0.3.1"
